config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root	'users#new'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :lists

  resources :lists do
    member do
        get :flop
        post :add_product
        put :remove_product
        get :search_product
        post :vote
        put :unvote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ActiveRecord::Base
  require_dependency("#{Rails.root}/lib/skroutzapi")
  belongs_to :user
  has_many :sku_lists
  has_many :list_votes
  has_many :vote_users, through: :list_votes, source: :user

  validates :name, presence: true, uniqueness: {scope: :user, case_sensitive: false}, length: {in: 3..50}
  validates :user_id, presence: true

  scope :visible, -> {where(private: false)}

  def list_total_price()
  	skroutz=Skroutzapi.new
    list_price = 0
    sku_lists.pluck(:sku_id).each do |variable|
      list_price +=  skroutz.search_sku_by_id(variable).price_min
    end
    list_price.round(2)
  end
end

app/models/list_vote.rb
class ListVote < ActiveRecord::Base
  belongs_to :list, counter_cache: :votes_count
  belongs_to :user

  validates :list, uniqueness: {scope: :user} 
end

app/models/sku_list.rb
class SkuList < ActiveRecord::Base
  belongs_to :list

  validates :sku_id, uniqueness: {scope: :list} 
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 

  has_many :lists, dependent: :destroy
  has_many :list_votes
  has_many :vote_lists, through: :list_votes, source: :list

  before_save { self.email = email.downcase }

  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false }, 
            length: { in: 3..25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false}, 
            length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 8 }, on: :create
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perfom this action"
      redirect_to root_path
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, except: [:new, :create, :index]
  before_action :require_same_user, only: [:edit, :update, :flop, :add_product, :remove_product]
  before_action :set_skroutz_connection, only: [:show, :add_product, :skus_associated_to_list, :search_product]
  before_action :skus_associated_to_list, only: [:show, :search_product, :products_for_pagination]
  before_action :products_for_pagination, only: [:show, :search_product]
  
  # Get /lists/new
  def new; end
  
  # Post /lists
  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      flash[:success] = "List was successfully created"
    else
      flash[:danger] = @list.errors.full_messages.first
    end
    redirect_to user_path(current_user)
  end
  
  # Get /lists/:id/edit
  def edit; end
  
  # Put /lists/:id
  def update
    if @list.update(list_params)
      flash[:success] = "List name was successfully updated"
    else
      flash[:danger] = @list.errors.full_messages.first
    end
    redirect_to user_path(current_user)
  end
  
  # Get /lists
  def index
    if params[:pagination_order].present? && params[:pagination_order]=="votes"
      @lists = List.visible.order("votes_count DESC").paginate(page: params[:page], per_page: 12)
    else
      params[:pagination_order]=""
      @lists = List.visible.order("created_at DESC").paginate(page: params[:page], per_page: 12)
    end
  end
  
  # Get /lists/:id
  def show; end
  
  # Delete /lists/:id
  def destroy
    @list.destroy
    flash[:danger] = "List was successfully deleted"
    redirect_to user_path(current_user)
  end
  
  # Get /lists/:id/flop
  def flop
    @list.private = !@list.private # flop the status
    if @list.save
      render json:{}, status: :ok
    else
      render json:{}, status: :unprocessable_entity
    end
  end
  
  #  POST   /lists/:id/add_product
  def add_product
    @sku_list=SkuList.new(sku_id: params[:skuid], list_id: @list.id)
    if !@sku_list.save
      skus_associated_to_list
    end
    redirect_to list_path(@list) 
  end
  
  # Put /lists/:id/remove_product
  def remove_product
    @list.sku_lists.where(sku_id: params[:skuid].to_i).destroy_all
    flash[:success]="Product deleted"
    redirect_to list_path(@list)
  end
  
  # Get /lists/:id/search_product
  def search_product
    @product=@skroutz.search_sku_by_id(params[:skuid])
    if !@product.present?
      flash[:danger]="This sku doesn't exist"
      return redirect_to list_path(@list)
    end
    @modal=true
    render 'show'
  end
  
  def vote
    list_vote=ListVote.new(list_id: @list.id, user_id: current_user.id)
    if list_vote.save
      flash[:success]="Thank you for voting"
    else
      flash[:danger]="Sorry your vote could not be saved"
    end
    redirect_to list_path(@list)
  end

  def unvote
    list_vote=ListVote.where(list_id: @list.id, user_id: current_user.id)
    list_vote.destroy_all
    redirect_to list_path(@list)
  end

  private
  def list_params  
    params.require(:list).permit(:name, :private)
  end

  def set_list
    @list = List.find(params[:id])
  end

  def require_same_user
    if current_user != @list.user && !current_user.admin?
      flash[:danger] = "You don't have permissions to view this page"
      redirect_to lists_path
    end
  end

  def set_skroutz_connection
    @skroutz=Skroutzapi.new
  end
  
  def skus_associated_to_list
    @products=[]
    @list.sku_lists.pluck(:sku_id).each do |variable|
      @products << @skroutz.search_sku_by_id(variable)
    end
  end  

  def products_for_pagination
    @list_products = @products.paginate(page: params[:page], per_page: 11)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
   @user = User.new
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
  	  session[:user_id] =user.id
      flash[:success] = "You have successfully logged in"
      redirect_to lists_path
    else
  	  flash[:danger] = "There was something wrong with your login information. Please Try again"
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :show, :destroy]
  before_action :require_admin, only: [:destroy]

  def new
    if logged_in?
      redirect_to user_path(current_user)
    else
      @user=User.new
    end
  end

  def create  
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      flash[:success]="Welcome to Skroutz Lists #{@user.username}"
      redirect_to lists_path
  	else
      render 'new'
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success]="User was successfully updated"
      redirect_to lists_path
    else
      render 'edit'
    end
  end

  def show
    @user_lists=@user.lists.order("created_at DESC").paginate(page: params[:page], per_page: 11)
  end

  private
  def user_params  
  	params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger]="You don't have permissions to view this page"
      redirect_to lists_path
    end
  end
  
  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger]="Only admin users can perfom that action"
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<div class="row display_msg">
  <div class="col-xs-10 col-xs-offset-1">
	<% flash.each do |name, msg|%>
  	  <div class='alert alert-<%= "#{name} "%> fade in'>
  	  	<a href="#" class="close" data-dismiss="alert">&#215;</a>
  	  	<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  	  </div>
    <% end %>
    <script>
      setTimeout("$('.display_msg').fadeOut('slow')", 3000)
    </script>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Lists", user_path(current_user), class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All lists", lists_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" 
               title="Profile options" ><%= current_user.username %> <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkroutzLists</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= render 'layouts/messages' %>
    <% if logged_in? %>
      <%= render 'layouts/navbar'%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_edit_modal.html.erb
<%= link_to "#", "data-toggle" => "modal", "data-target"=>"#editModal--effect-zoomIn", :title => "Rename list", class: "btn btn-xs               pencilglyphicon" do %>
  <span class="glyphicon glyphicon-pencil"></span>
<% end %>

<div id="editModal--effect-zoomIn" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit</h4>
      </div>
      <div class="modal-body">
        <%= form_for list, url: list_path(list.id), :html => {class: "form-horizontal", role: "form"} do |f| %>
        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.text_field :name, class: "form-control", placeholder: "e.g Running shoes", autofocus: true %>
          </div>
        </div>
        <div class="checkbox col-md-offset-1">
          <label><%= f.check_box :private %>Private list</label>
        </div>
        <div>
          <%= f.submit "Update", class: 'btn btn-primary btn-sm  col-sm-offset-5  ' %> 
        </div>
      <% end %>
      </div>
      
    </div>
  </div>
</div>

app/views/lists/_product_modal.html.erb
<!-- Modal -->
<div id="myModal--effect-zoomIn" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= @product.name %></h4>
      </div>
      <div class="modal-body">
        <img src="<%= @product.images["main"]%>">
        <small class="trashglyphicon">
          <%= @skroutz.find_sku_category(@product.category_id).name %>
        </small>
      </div>
      <div class="modal-footer">
        <div class="modal_div_footer">
          <small>
            <p>Price: <%= @product.price_min%> --> <%= @product.price_max%> &#8364;</p>
          </small>
        </div>
        <%= button_to"Add to list", add_product_list_path(@list, skuid: @product.id), class: "btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<h1 align="center">All Lists</h1>
<div align="center">
  <%= will_paginate %>
</div>  
<div align="center" >
  <% if !params[:pagination_order].present? %>
    <%= link_to "Sort by: Votes", lists_path(pagination_order: "votes") %>
  <% else %>
    <%= link_to "Sort by: Date", lists_path()%>
  <% end %>
</div>
<div class="row">
  <% @lists.visible.each do |list| %>
    <div class="col-sm-6 col-md-2">
      <div class="list_div">
        <%= link_to list.name, list_path(list) %>
        <p>Total price: <%= list.list_total_price %> &#8364;</p>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/show.html.erb
<%= render 'shared/errors', obj: @sku_list if @sku_list.present? %>
<%if @modal==true%><%= render 'product_modal'%><%end%>


<div align="center">
  <%= will_paginate @list_products %>
</div>


<div class="row">
  <div class="col-sm-6 col-md-2">
    <div class="list_div">
      <p id="p02"><%= @list.name %></p>
      <% if current_user == @list.user %>
        <small class="js-private <%= "hidden" if !@list.private? %>" data-list="<%= @list.id %>" title="Click to change status" >
  	      private
        </small>
        <small class="js-visible <%= "hidden" if @list.private? %>" data-list="<%= @list.id %>" title="Click to change status">
  	      visible
        </small>
        <%= form_tag search_product_list_path(@list), method: :get do %>
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-1">
              <%= text_field_tag :skuid, params[:skuid], placeholder: "skuid", autofocus: true %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 col-sm-offset-4">
               <%= button_to "Search", search_product_list_path, class: "btn btn-primary btn-sm" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>User: <%= @list.user.username%></p>
        <% if !current_user.vote_lists.exists?(@list.id) %>
          <%= link_to vote_list_path(@list), class: "btn btn-lg", method: :post do %>
            <span class="glyphicon glyphicon-thumbs-up"></span>
          <% end %>
        <% else %>
          <%= link_to unvote_list_path(@list), class: "btn btn-lg", method: :put do %>
            <span class="glyphicon glyphicon-thumbs-down"></span>
          <% end %>
        <% end %>
      <% end %>
      <div class="footer">
        <p>Total price: <%= @list.list_total_price %> &#8364;</p>
        <p><small>Created at: <%= time_ago_in_words(@list.created_at) %> ago</small><p>
        <p><small>Last updated at: <%= time_ago_in_words(@list.updated_at) %> ago</small></p>
      </div> 
    </div>
  </div>                            

  <% @list_products.each do |product| %>
    <div class="col-sm-6 col-md-2">
      <div class="list_div">
        <small>
          <%= @skroutz.find_sku_category(product.category_id).name %>
        </small>
        <% if current_user == @list.user %>
          <%= link_to remove_product_list_path(@list, skuid: product.id), class: "btn btn-xs trashglyphicon", 
            method: :put, data: {confirm: "Are you sure you want to delete this product from the list?"} do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        <% end %>
        <div>
          <img src="<%= product.images["main"]%>">
        </div>
        <div>
          <%= product.name %>
        </div>  
        <small>
            <p>Price: from <%= product.price_min%> &#8364;</p>
          </small>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#myModal--effect-zoomIn').modal('show');
    $(".js-visible, .js-private").on('click', function(){
      $.ajax({
        url:"/lists/"+$(this).data("list")+"/flop",
        success: function(data){
          $(".js-private").toggleClass("hidden");
          $(".js-visible").toggleClass("hidden");
        }
      });
    }); 
  });
</script>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-10">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg|%>
                <li><%= msg%></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :password_confirmation %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Re-enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: 'btn btn-primary btn-sm') %>
          <%= link_to "Cancel", root_path, class: 'btn btn-primary btn-sm',
               data: {confirm: "Are you sure you want to cancel and return to homepage?"}%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_login_modal.html.erb
<div class="row">
  <div class="col-sm-10 center">
    <p id="p01">or</p>
    Already have an account? 
    <a href="#" data-toggle="modal" data-target="#myModal--effect-zoomIn">Log in</a>
  </div>
</div>
<!-- Modal -->
<div id="myModal--effect-zoomIn" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Log in</h4>
      </div>
      <%= form_for(:session, :html => {class: "form-horizontal", role: "form"}, url: login_path) do |f| %>
        <div class="form-group custom_modal_field">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.password_field :password, class: "form-control", placeholder: "Password", autocomplete: "off" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-1 col-sm-10 center">
            <%= f.submit "Log in", class: 'btn btn-primary btn-sm' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 col-md-7 col-md-offset-1">
    <div class="thumbnail thumbnail_left">
    </div>
  </div>
  <div class="col-sm-6 col-md-4 thumbnail_right">
  	<%= render 'shared/errors', obj: @user %>
  	<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-5">
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
        <div class="col-sm-5">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Re-enter password" %>
        </div>
      </div>
      <div>
        <%= f.submit "Sign up", class: 'btn btn-primary btn-sm col-sm-10' %> 
      </div>
    <% end %>
    <%= render 'login_modal' %>
  </div>
</div>

app/views/users/show.html.erb
<h1 align="center">My Lists</h1>

<div align="center">
  <%= will_paginate @user_lists%>
</div>
<div class="row">
  <div class="col-sm-6 col-md-2">
  	<div class="create_list_div">
      <p id="p02">Create a list. Start by entering a name </p>
      <%= form_for :list, url: lists_path, :html => {class: "form-horizontal", role: "form"} do |f| %>
        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.text_field :name, class: "form-control", placeholder: "e.g Running shoes", autofocus: true %>
          </div>
        </div>
        <div class="checkbox col-md-offset-1">
          <label><%= f.check_box :private %>Private list</label>
        </div>
        <div>
          <%= f.submit "Create list", class: 'btn btn-primary btn-sm col-sm-10 col-sm-offset-1' %> 
        </div>
      <% end %>
    </div>
  </div>
  <% @user_lists.each do |list| %>
    <div class="col-sm-6 col-md-2">
      <div class="list_div">
        <%= render 'lists/edit_modal', list: list %>
        <%= link_to list.name, list_path(list) %>
        <%= link_to list_path(list), :title => "Delete list", class: "btn btn-xs trashglyphicon", 
          method: :delete, data: {confirm: "Are you sure you want to delete this list?"} do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
        <p>Total price: <%= list.list_total_price %> &#8364;</p>
      </div>
    </div>
  <% end %>
</div>